trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  phpVersion: 8.0

steps:
- script: |
    sudo add-apt-repository ppa:ondrej/php
    sudo apt-get update
    sudo apt install php8.0-common php8.0-cli php8.0-{mbstring,mysqli,dom} -y
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'PHP $(phpVersion) install'

- script: |
    composer install --no-interaction --prefer-dist
  displayName: 'composer install'

- script: |
    php -d zend.assertions=1 vendor/bin/phpunit tests
  displayName: 'Run phpunit'

- script: |
    vendor/bin/phpstan analyze
  displayName: 'Run phpstan'
